// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.0;

import 'solidity-kit/solc_0.8/ERC20/implementations/ERC20Base.sol';
import 'solidity-kit/solc_0.8/ERC20/ERC2612/implementations/UsingPermitWithDynamicChainID.sol';

/// @title Gems Tokens
/// @author Ronan Sandford
/// @notice Gems Tokens initialy generated by playing instances of Stratagems
contract Gems is ERC20Base, UsingPermitWithDynamicChainID {
	constructor(address to, uint256 amount) UsingPermitWithDynamicChainID(address(this)) {
		_mint(to, amount);
	}

	string public constant symbol = 'GEM';

	function name() public pure override(IERC20, Named) returns (string memory) {
		return 'Gems';
	}
}
