name = "fuzd-cf-worker"
main = "node_modules/fuzd-cf-worker/src/worker.ts"
compatibility_date = "2023-08-14"

compatibility_flags = [ "nodejs_compat" ] # for node:async_hooks

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "fuzd-db"
database_id = "3b9d30e7-6f33-4607-b4cd-4448e4d88951"

[triggers]
crons = ["* * * * *", "*/1 * * * *"]
